# Generated by Django 3.2.9 on 2021-11-21 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialmediasettings',
            name='instagram',
        ),
        migrations.AddField(
            model_name='socialmediasettings',
            name='linkedin',
            field=models.URLField(default='field', help_text='Your Linkedin page URL'),
            preserve_default=False,
        ),
    ]
