# Generated by Django 3.2.9 on 2021-11-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpage',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
